{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "vllm-inference.namespace" . }}
  labels:
    name: {{ include "vllm-inference.namespace" . }}
{{- with .Values.namespace.labels }}
{{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}
