{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.resourceNames.serviceMonitor }}
  namespace: {{ include "vllm-inference.namespace" . }}
  labels:
{{ include "vllm-inference.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.selectorLabels.app }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
